### ISSUE TITLE
Good Ol See "systemctl status wg-quick@wg0.service"

### ISSUE THREAD

**Issue by ShadiestGoat** [angristan/wireguard-install#131]
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

Thats what I get if I try to set this up on my vps. If I do the suggested commands:

wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-09-07 14:44:39 PDT; 13s ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
  Process: 13137 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=1/FAILURE)
 Main PID: 13137 (code=exited, status=1/FAILURE)
Sep 07 14:44:39 Host systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Sep 07 14:44:39 Host wg-quick[13137]: [#] ip link add wg0 type wireguard
Sep 07 14:44:39 Host wg-quick[13137]: RTNETLINK answers: Operation not supported
Sep 07 14:44:39 Host wg-quick[13137]: Unable to access interface: Protocol not supported
Sep 07 14:44:39 Host wg-quick[13137]: [#] ip link delete dev wg0
Sep 07 14:44:39 Host wg-quick[13137]: Cannot find device "wg0"
Sep 07 14:44:39 Host systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 14:44:39 Host systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
Sep 07 14:44:39 Host systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.

Now, I know this issue has been reported before with the final solution of just reinstalling the packages, but, I've tried this with no success. I have also tried just rebooting the vps, but like that just fucks up my DNSs in my resolv.conf file. I have to re do that file, because like half the internet capabilities just go poof. Is there a fix for this?

**Comment by randomshell** [comment]
I suppose you are on a Debian based distro #125? The other distros should work.

**Comment by ShadiestGoat** [comment]
Heya! Yeah you are completely right, and the issues I'm facing are the exact ones that are there. However,  I can't really find a way to install the kernel headers, I'm a bit new ot ubuntu, so how do I do that?
if i do `sudo apt install linux-headers-$(uname -r)` then it says Im on the latest version..
`linux-headers-4.15.0-22-generic is already the newest version (4.15.0-22.24).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
Running on Ubuntu 18.04

**Comment by randomshell** [comment]
> if i do sudo apt install linux-headers-$(uname -r) then it says Im on the latest version..

Can you paste the output of `dkms status`?

I don't know what to suggest other than upgrading the packages, installing `linux-headers`, reinstalling WireGuard and reboot.

> I have also tried just rebooting the vps, but like that just fucks up my DNSs in my resolv.conf file. I have to re do that file, because like half the internet capabilities just go poof. Is there a fix for this?

You probably don't want to manually edit `/etc/resolv.conf` for that reason.

**Comment by hybtoy** [comment]
@ShadiestGoat 
Did you try to reinstall wireguard? 
`apt-get install --reinstall wireguard-dkms`

**Comment by ShadiestGoat** [comment]
hey yall! Sorry for responding so late, my computer went brr and died completly on me. 

> Can you paste the output of `dkms status`?
wireguard, 1.0.20200611: added
> `apt-get install --reinstall wireguard-dkms`

Error! Bad return status for module build on kernel: 4.15.0-22-generic (x86_64)
Consult /var/lib/dkms/wireguard/1.0.20200611/build/make.log for more information.

the make.log:

DKMS make.log for wireguard-1.0.20200611 for kernel 4.15.0-22-generic (x86_64)
Mon Sep 14 02:56:28 PDT 2020
make: Entering directory '/usr/src/linux-headers-4.15.0-22-generic'
Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/main.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/noise.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/device.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/peer.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/timers.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/queueing.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/send.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/receive.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/socket.o
/var/lib/dkms/wireguard/1.0.20200611/build/socket.c: In function ‘send6’:
/var/lib/dkms/wireguard/1.0.20200611/build/socket.c:139:20: error: ‘const struct ipv6_stub’ has no member named ‘ipv6_dst_lookup_flow’; did you mean ‘ipv6_dst_lookup’?
   dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,
                    ^~~~~~~~~~~~~~~~~~~~
                    ipv6_dst_lookup
scripts/Makefile.build:332: recipe for target '/var/lib/dkms/wireguard/1.0.20200611/build/socket.o' failed
make[1]: *** [/var/lib/dkms/wireguard/1.0.20200611/build/socket.o] Error 1
Makefile:1552: recipe for target '_module_/var/lib/dkms/wireguard/1.0.20200611/build' failed
make: *** [_module_/var/lib/dkms/wireguard/1.0.20200611/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-22-generic'

**Comment by randomshell** [comment]
> Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"

Have you tried installing those packages? After that reinstall wireguard.

**Comment by ShadiestGoat** [comment]
> Have you tried installing one of those packages? After that reinstall wireguard.
goddamit T_T
Well no, I did that now. The root cause is still there though.

`DKMS make.log for wireguard-1.0.20200611 for kernel 4.15.0-22-generic (x86_64)
Tue Sep 15 12:41:08 PDT 2020
make: Entering directory '/usr/src/linux-headers-4.15.0-22-generic'
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/main.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/noise.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/device.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/peer.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/timers.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/queueing.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/send.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/receive.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/socket.o
/var/lib/dkms/wireguard/1.0.20200611/build/socket.c: In function ‘send6’:
/var/lib/dkms/wireguard/1.0.20200611/build/socket.c:139:20: error: ‘const struc$
   dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,
                    ^~~~~~~~~~~~~~~~~~~~
                    ipv6_dst_lookup
scripts/Makefile.build:332: recipe for target '/var/lib/dkms/wireguard/1.0.2020$
make[1]: *** [/var/lib/dkms/wireguard/1.0.20200611/build/socket.o] Error 1
Makefile:1552: recipe for target '_module_/var/lib/dkms/wireguard/1.0.20200611/$
make: *** [_module_/var/lib/dkms/wireguard/1.0.20200611/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-22-generic'`

**Comment by randomshell** [comment]
It should work after upgrading, as reported in #140

**Comment by ShadiestGoat** [comment]
Ah it works now, using another vps. Im not sure what happened ://
